### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/Hippocampe#19]
Hi ! 

After launching Hippocamp's boot command, when I go to 127.0.0.1:5000, the browser returns error 404

Why ? How to fix it ?

Have a great day

**Comment by ninSmith** [comment]
Hi bjuditt,

Have you tried to got to ```http://127.0.0.1:5000/hippocampe``` ?

If it still does not work could you please give us more details about how you launch it ?    
Could you also precise your elasticsearch server version ?

Thanks in advance.

**Comment by bjuditt** [comment]
Thank you for your prompt response ! Indeed that was the "problem".

Thanks again and have a nice day
