### ISSUE TITLE
All is empty 

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/Hippocampe#20]
Re !

Now that Hippocampe works, I wanted to add data but I can not click anywhere. I can not do anything with Hippocampe at the moment

![pbhippocampepng](https://cloud.githubusercontent.com/assets/25320209/22254067/e136cec8-e253-11e6-99cb-5f78cdab1b58.PNG)
![pbhippocampe2](https://cloud.githubusercontent.com/assets/25320209/22254072/e4f82156-e253-11e6-820e-379c9ffe34ce.PNG)

**Comment by ninSmith** [comment]
Hi again,

This behavior is normal.    

The dropdowns show data types available in Hippocampe.     
I guess that you have not launch an indexation (through the shadowbook button) yet.    
That means no data yet and no data types so empty dropdowns.    

Try to index first and wait until the job finished (check the jobs tab).     

Get back to me after so I can close the issue.

**Comment by bjuditt** [comment]
Hello ! 

When I click on the shadowbook button, a red bar appears, it must be an error but not displayed.

![pbhippocampe3](https://cloud.githubusercontent.com/assets/25320209/22282455/cd65279e-e2dc-11e6-9ab4-1f0927298c7b.PNG)

**Comment by ninSmith** [comment]
Humm strange...    

What is the Hippocampe's version ? Is the master one or the 1.0.0 ?   

Moreover, what is your elasticsearch server version ?

**Comment by bjuditt** [comment]
Where do we find this information?

**Comment by bjuditt** [comment]
For elasticsearch : 

![elasticsearch](https://cloud.githubusercontent.com/assets/25320209/22286269/db8b6452-e2ee-11e6-9602-083b2e9d3a5b.PNG)

**Comment by ninSmith** [comment]
If you "classically" cloned the project, you must have the master version.     

This version works with elasticsearch 5.1 and you have a 2.4 version.     

Try to upgrade your elasticsearch and let me know if it works.

**Comment by bjuditt** [comment]
Indeed, it was indeed a version error of elasticsearch !
However, when I run shadowbook, no job appears. Is this normal ?

**Comment by ninSmith** [comment]
Did you have the green pop up notification after pushing the button ?    

Could you send us a screenshot of the jobs tab ?

**Comment by bjuditt** [comment]
Yes I have the green pop up that tells me that the job was launched but I do not see anything. Moreover if I recict after, I have the message "ongoing job already running"

Screen : 
![jobhippo](https://cloud.githubusercontent.com/assets/25320209/22290790/2f529fa6-e303-11e6-8973-24afeaabb703.PNG)

**Comment by ninSmith** [comment]
How did you install the 5.1 elasticsearch version and did you uninstall the 2.4 ?    

Maybe the 5.1 keeps the old data from 2.4...     

Try to delete any Hippocampe's record with:    
```
curl -XDELETE localhost:9200/hippocampe
```

And try to index again with ```shadowbook```

**Comment by bjuditt** [comment]
Unfortunately, still no change. I will reinstall it with the correct version this time and I will keep you updated

**Comment by ninSmith** [comment]
Ok, I close this issue but feel free to open another one.

Thanks
