### ISSUE TITLE
Run as a service

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/Hippocampe#24]
Hello !

Have you a solution to execute Hippocampe as a service ?

Thank you

**Comment by ninSmith** [comment]
Hi,

Yes we have but is still in draft mode for the moment.    
We will formalize that as soon as possible in the docs and let you know.

However if you can't wait, take a look at these two links:

http://vladikk.com/2013/09/12/serving-flask-with-nginx-on-ubuntu/
http://serverfault.com/questions/775965/wiring-uwsgi-to-work-with-django-and-nginx-on-ubuntu-16-04

Thanks

**Comment by bjuditt** [comment]
Thank you, but not understanding these documentations, I will wait for yours.

**Comment by ninSmith** [comment]
Hi bjuditt,

Please find the documentation at https://github.com/CERT-BDF/Hippocampe/blob/master/docs/install_guide.md#hippocampe-as-a-service

Make sure to use the new version of ```app.py``` since it has been modified to work as a service.

Thanks.
