### ISSUE TITLE
Formula of Hipposcore

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/Hippocampe#25]
Is it possible to have the calculation formula of Hipposcore? The link on the following url is dead.

Thank you

https://github.com/CERT-BDF/Hippocampe/blob/master/docs/api_guide.md#hipposcore

Also, I always get the impression that it is equal to -86.47 ...

**Comment by ninSmith** [comment]
Hey,   

You can find the formula here: https://github.com/CERT-BDF/Hippocampe/blob/master/core/services/hipposcore.py

It is ```score = (1 - exp(-2 * abs(P))) * (abs(P) / P) * 100```   

With:

```
#P is the sum of n3 * n2 * n1 for every matches
P = P + (n3 * n2 * n1)
```

And :

```
n1: source's score
n2: 1 (will change in a feature request)
n3: exp(- intel's age in days / 182.625)
```

We will update the doc to be more explicit about the formula.

Thanks
