### ISSUE TITLE
Hippocampe as a service

### ISSUE THREAD

**Issue by bjuditt** [CERT-BDF/Hippocampe#27]
Hello, i want to try to run Hippocampe as a service with your documentation but at the end; i've the message "Internal Server Error"

Can you point me to a solution.

Thanks

**Comment by bjuditt** [comment]
EDIT : I just saw in the log `/var/www/demoapp/log/uwsgi/demoapp_uwsgi.log` that the error was 
```
File "./app.py", line 4, in <module>
from flask import Flask [.....]
ImportError: No module named flask
```

While the program works very well manually

**Comment by ninSmith** [comment]
Hum strange, what's your OS and OS version ?

Thanks

**Comment by bjuditt** [comment]
Ubuntu 16.04 lts, to solve this problem I have to download python-flask (not with pip) but after that I was asked for each module to be imported. I gave up. I thought you would have an idea

**Comment by ninSmith** [comment]
We will try to reproduce your problem and keep you updated.

Thanks

**Comment by bjuditt** [comment]
Ok thanks

**Comment by bjuditt** [comment]
Hi !

Do you have something new ?

**Comment by ninSmith** [comment]
Hi bjuditt,

We were unable to reproduce the issue but from what you tell, it might be a python version issue...

From the command line you seem to use python2 with all dependencies installed.     
uWSGI may use python3 and you did not install flask for python3, that would explain what you got...   

So now we have to confirm this hypothesis, could you execute the following and gave us the output:

* ```/usr/bin/env python -V```
*  ```pip -V```

Finally, how did you install uWSGI ?

Thanks

**Comment by bjuditt** [comment]
For UWSGI, I followed line by line your documentation.

Result of the command : 

```
ubuntu@ubuntu: ~$ /usr/bin/env python -V
Python 2.7.12

```
```
ubuntu@ubuntu: ~$ pip -V
pip 9.0.1 from /home/me/.local/lib/python2.7/sites-packages (Python 2.7)
```

**Comment by ninSmith** [comment]
Could you please join us on https://gitter.im/TheHive-Project/TheHive ?

That way we could communicate more easily and hopefully resolve your issue.

Thanks.
