### ISSUE TITLE
Problems with ES2.4.5 with Hippocampe

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/Hippocampe#34]
### Request Type
Bug
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 8
| OS version (client)       | Ubuntu
| Hippocampe version / git hash   | https://github.com/CERT-BDF/Hippocampe/commit/9888ed1e27cb1c758af68ec8e6add0ca060b4768
| Package Type              | Binary
| Browser type & version    | n.a.

### Problem Description
Hippocampe seems not to work.

### Steps to Reproduce
-Installation was done as described in Install procedure on the same host as TheHive runs.
-Hippocampe was configured to run as Service with UWSGI
-Additional hippocampe was started on console (as port 5000 was not bound by "python app.py")
-First query was placed:
curl -XGET localhost:5000/hippocampe/api/v1.0/shadowbook
-Result on console is:

[2017-05-12 11:57:45,218] ERROR in app: Exception on /hippocampe/api/v1.0/shadowbook [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 168, in shadowbookService
    if 'error' in reportJob:
TypeError: argument of type 'NoneType' is not iterable
127.0.0.1 - - [12/May/2017 11:57:45] "GET /hippocampe/api/v1.0/shadowbook HTTP/1.1" 500 -

### Complementary Information
Index seems to exist:
user1:~# curl 'http://localhost:9200/_cat/indices?v'
health status index      pri rep docs.count docs.deleted store.size pri.store.size
yellow open   hippocampe   5   1          0            0       795b           795b
yellow open   the_hive_8   5   1       4999            1      3.1mb          3.1mb

**Comment by AlexFaraino** [comment]
Hi crackytsi,
Hippocampe has been updated from Elasticsearch 1.x to 5.1.x and never was compatible with 2.x.

See Issue #9

**Comment by crackytsi** [comment]
Thank you.
I did not really understand that:
What about thehive? The Default describes install of Version 2..
Are both products compatible to ES5?

**Comment by AlexFaraino** [comment]
Not yet : https://github.com/CERT-BDF/TheHive/issues/82

**Comment by crackytsi** [comment]
Sorry for asking once more.
I did not get that at all.
Is there any ES Version that works together with Hippocampe AND with TheHive?

**Comment by ninSmith** [comment]
Dear crackytsi,

Currently if you would like to use TheHive **and** Hippocampe, you will have to install **2** elasticsearch servers.   

Elasticsearch 2.X for TheHive and elasticsearch 5 for Hippocampe.
As said AlexFaraino, the upgrade to elasticsearch 5 for TheHive is ongoing.

Feel free to ask any additional questions you may have.

@AlexFaraino thanks for answering ;)
