### ISSUE TITLE
Develop Dockerfille won't build NPM not installed as part of Nodejs

### ISSUE THREAD

**Issue by rayschippers** [CERT-BDF/Hippocampe#40]
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Docker build
| OS version (client)       |  N/a
| Hippocampe version / git hash   |  8055289 (develop branch)
| Package Type              | Docker
| Browser type & version    | N/a

### Problem Description
Dockerfile build errors with /bin/sh: npm: not found
### Steps to Reproduce
1. Checkout develop branch
2. docker build .

### Possible Solutions
Install nodejs-npm package in Dockerfile (as per my commit)

**Comment by ninSmith** [comment]
Dear @rayschippers 

Thank you for raising this issue.

We are aware of this bug and are looking into it.

From our test, it works with docker 17.05.0 and docker compose 1.12.0.
It doesn't work with docker 17.03.1 and docker compose 1.13.0.

Will keep you updated.
