### ISSUE TITLE
Feature Request: Alerting for Networks

### ISSUE THREAD

**Issue by crackytsi** [CERT-BDF/Hippocampe#42]
### Request Type
Feature Request

### Problem Description
It would be great, if I could add networks ranges of my internet facing devices and Hippocampe would Alert (e.g. in a log-file) if IPs from within this range were listed on a feed

**Comment by ninSmith** [comment]
Dear @crackytsi,

Thanks for your issue.

Unfortunately, your use-case is not in the scope of Hippocampe.
Hippocampe is not made for monitoring IPs within feeds.

However, you could easily develop a script which does that thanks to Hippocampe API.

I close this issue but feel free to re-open it if you disagree with my point of view.

Danni
