### ISSUE TITLE
Hippocampe Errors on ImportError: No module named configparser

### ISSUE THREAD

**Issue by darksheer** [CERT-BDF/Hippocampe#47]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.4 LTS
| OS version (client)       | OS X
| Hippocampe version / git hash   | Latest
| Package Type              | From source
| Browser type & version    | N/A

### Problem Description
When executing the app.py script, the following error is produced. 

```
Traceback (most recent call last):
  File "./app.py", line 5, in <module>
    from services import shadowbook, hipposcore, more, distinct, typeIntel, new, sources, hipposched, freshness, schedReport, lastQuery, sizeBySources, sizeByType, monitorSources, jobs, lastStatus
  File "/opt/Hippocampe/core/services/shadowbook.py", line 8, in <module>
    from modules.shadowbook import createSessions
  File "/opt/Hippocampe/core/services/modules/shadowbook/createSessions.py", line 10, in <module>
    from getConf import getConf
  File "/opt/Hippocampe/core/services/modules/shadowbook/../../../services/modules/common/getConf.py", line 4, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser
```

### Steps to Reproduce
1. Follow the install steps in the docs. 
2. Execute the app.py script.
3. Error returned

### Possible Solutions
Unknown  Module is installed for both python2 / python3

**Comment by ninSmith** [comment]
Hey,

Could you try:

```
sudo pip install elasticsearch Configparser netaddr flask python-dateutil apscheduler requests
```

and execute app.py again ?

Thx

**Comment by darksheer** [comment]
@ninSmith Sorry, I forgot to get back to this one.  Apparently, with the install of theHive, Cortex, and others, the default version of Python was pushed up, which required installing via pip2.7, not pip2 (system default). 

Resolving since I wasn't paying close enough attention to the multiple different versions of Python needed to install the suite of utilities.
