### ISSUE TITLE
Upgrade to Elasticsearch v2/v5

### ISSUE THREAD

**Issue by AlexFaraino** [CERT-BDF/Hippocampe#9]
Elasticsearch support for v.1.7 is reaching its end in January: https://www.elastic.co/fr/support/eol
I tried to use v.2.4, but got an unexpected behavior: job is never updated and stays ongoing for ever.
```
{
  "AVkrJKJo4Y9D2h2GY9yi": {
    "startTime": "20161223T100538+0000",
    "status": "ongoing"
  }
}
```
Looking at the logs, it seams that something is silently failing: 
```
services.shadowbook :: INFO :: shadowbook.startJob end
services.shadowbook :: INFO :: shadowbook.updateJob launched
services.shadowbook :: INFO :: updating with status: done
```
From /core/services/shadowbook.py
```
def updateJob(report, status):
	logger.info('shadowbook.updateJob launched')
	logger.info('updating with status: %s', status)
	#update job status, add the report and calculates the duration
	job = Job()
	job.updateStatus(report, status)
	logger.info('shadowbook.updateJob end')
```
And I never got this log: 
```
services.shadowbook :: INFO :: shadowbook.updateJob launched
```

Did you already tried to upgrade to a more recent version of ES (v.2.x or v.5.x) ?
Did you encounter some blocking issues?

**Comment by ninSmith** [comment]
Hi Alex,   

Thanks for submitting this issue.   

We managed to reproduce your bug using Elasticsearch 5.1.1 and it appears that upgrading the search engine also "breaks" several services:

* distinct
* lastStatus
* new
* sizeByType
* type

Unfortunately,  there is no workaround yet...    
We will work on this compatibility issue and will keep you updated through this issue.

**Comment by AlexFaraino** [comment]
Hi,
Have you seen the compatibility note on the elasticsearch python module: https://pypi.python.org/pypi/elasticsearch/5.0.1
> The library is compatible with all Elasticsearch versions since 0.90.x but you have to use a matching major version:
> For Elasticsearch 5.0 and later, use the major version 5 (5.x.y) of the library.
> For Elasticsearch 2.0 and later, use the major version 2 (2.x.y) of the library.
> For Elasticsearch 1.0 and later, use the major version 1 (1.x.y) of the library.
> For Elasticsearch 0.90.x, use a version from 0.4.x releases of the library.

Hopping it will help you.
-- 
Alex

**Comment by ninSmith** [comment]
The following issues are related to the compability issue with Elasticsearch 5:

- [ ] With Elasticsearch 5, shadowbook fails: "script or doc is missing"

**Comment by ninSmith** [comment]
Hi Alex,

Thank you for your patience.     

The current version of Hippocampe should now work with Elasticsearch 5.1    

Give it a try and feel free to submit any other issue you may find :)
